### ISSUE TITLE
Doens't work in production

### ISSUE THREAD

**Issue by Power-Howdy** [lukas-reining/eventsource#3]
This is working fine on local development, when I run angular app on localhost:4200,
However, once I deploy the app to the vercel, it returns error.

```
main-6FYVCRR5.js:7 ERROR TypeError: (void 0) is not a constructor
    at e.getEventSource (main-6FYVCRR5.js:18:4128)
    at i._subscribe (main-6FYVCRR5.js:18:3856)
    at i._trySubscribe (main-6FYVCRR5.js:3:4428)
    at main-6FYVCRR5.js:3:4373
    at Ua (main-6FYVCRR5.js:3:2222)
    at i.subscribe (main-6FYVCRR5.js:3:4289)
    at e.<anonymous> (main-6FYVCRR5.js:18:11341)
    at Generator.next (<anonymous>)
    at chunk-2WQGNY7Y.js:1:1640
    at new t (polyfills-LZBJRJJE.js:2:2128)
```
    
     this is the compiled source which I can see in devtools

```
            getEventSource(t) {
            return new (void 0)(t,{
                headers: {
                    Authorization: "Bearer " + this.token
                },
                retry: 3e3
            })
        }
```
        
        here's my source code 
        
 ```
 import { Injectable, NgZone, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { apiUrl } from '../../environment';
import { AuthRegularService } from '../services/auth-regular.service';
import { EventSource as CustomEventSource } from 'extended-eventsource';

@Injectable({
  providedIn: 'root',
})
export class SseService {
  token = inject(AuthRegularService).getToken();
  constructor(private _zone: NgZone) {}
  getServerSentEvent(url: string): Observable<any> {
    return Observable.create((observer: any) => {
      const eventSource = this.getEventSource(url);
      eventSource.onmessage = (event) => {
        this._zone.run(() => {
          // console.log("SSE event data received: ", event.data)
          if (!event.data) {
            console.log('False data received', event.data);
            // do not forward as this causes an error, "", false, undefined, null
          } else if (JSON.parse(event.data).msg === 'PROCESS_ENDED') {
            eventSource.close();
            observer.next(event);
          } else {
            observer.next(event);
          }
        });
      };
      eventSource.onerror = (error: any) => {
        console.log('Getting server sent event error:', error);
        eventSource.close();
        return;
        // this._zone.run(() => {
        //   observer.error(error);
        // });
      };
    });
  }

  private getEventSource(url: string): EventSource {
    return new CustomEventSource(url, {
      headers: {
        Authorization: 'Bearer ' + this.token,
      },
      retry: 3000,
    });
  }
}

```

**Comment by lukas-reining** [comment]
Hey @Power-Howdy can you give some info on how you build or provide a small example?
I can not reproduce it right now.

**Comment by lukas-reining** [comment]
@Power-Howdy I just published a version that should work based on @dargmuesli's change.
Would be happy to know if your issue has been fixed!
